name: flutter_admob_kit
description: Lightweight Google Mobile Ads wrapper for Flutter with UMP consent, automatic preloading, premium gating, banners, native templates, and fullscreen ads.
version: 4.0.0
homepage: https://github.com/AmeerHamza-9902/flutter_admob_kit
repository: https://github.com/AmeerHamza-9902/flutter_admob_kit
issue_tracker: https://github.com/AmeerHamza-9902/flutter_admob_kit/issues

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.1'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: '>=9.1.0 <10.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - admob
  - ads
  - monetization
  - interstitial
  - rewarded

flutter:
  plugin:
    platforms:
      android:
        package: dev.admobkit.flutter_admob_kit
        pluginClass: FlutterAdmobKitPlugin
